### ISSUE TITLE
Sound recorder app package name isn't correct.

### ISSUE THREAD

**Issue by MF-Debug** [Thrilleratplay/LOSdiet#6]
the sound recorder app package name contains the old cm13.1 name. with new LOS14.1, it is changed. please correct this.

**Comment by Thrilleratplay** [comment]
This package has been confusing.  There still seems to be a [SoundRecorder package still being used and maintained](https://github.com/search?q=org%3ALineageOS+SoundRecorder&type=Code) but there is a newer app called [Recorder](https://github.com/LineageOS/android_packages_apps_Recorder) which looked like it is may replace SoundRecorder or is just going to handle screen recording.

In either case, I am working on creating a more thorough and robust list.  I hope to have this done within the week depending on my schedule.

**Comment by Thrilleratplay** [comment]
@killoid The update with both Recorder and SoundRecorder as options has been pushed.
